<?php
// $Id: revisions_rss.install,v 1.3 2010/02/25 21:50:14 alexj Exp $

/**
 * @file
 * Provides install and uninstall functions for revisions_rss.
 */

/**
 * Implementation of hook_uninstall().
 */
function revisions_rss_uninstall() {
  variable_del('revisions_rss_nodetypes');
}

/**
 * Renamed variable.
 */
function revisions_rss_update_6160() {
  variable_set('revisions_rss_nodetypes', variable_get('revision_rss_nodetypes', array('page')));
  variable_del('revision_rss_nodetypes');
}