<?php
// $Id: revisions_rss.module,v 1.5 2010/02/23 18:28:59 alexj Exp $

/**
 * @file
 * Revision RSS, written by Alex Jarvis
 */

define('REV_RSS_PERM', 'view revision rss');

/*
 * Adds a permission for viewing RSS revisions.
 */
function revisions_rss_perm() {
  return array(REV_RSS_PERM);
}

/**
 * Implementation of hook_menu().
 */
function revisions_rss_menu() {
  $items = array();

  $items['admin/content/rss-publishing/default'] = array(
    'title' => 'General settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/content/rss-publishing/revision-rss'] = array(
    'title' => 'Revision RSS publishing',
    'description' => 'Configure RSS feeds for revisions.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('revision_rss_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'file' => 'revisions_rss.admin.inc',
  );
  $items['node/%node/revisions/rss'] = array(
    'title' => '',
    'page callback' => '_revisions_rss_format_feed',
    'page arguments' => array(1),
    'access arguments' => array(REV_RSS_PERM),
    'type' => MENU_CALLBACK,
    'file' => 'revisions_rss.pages.inc',
  );

  return $items;
}

function revisions_rss_nodeapi(&$node, $op, $teaser, $page) {
  if(user_access(REV_RSS_PERM) && $op == 'view' && !$teaser && $page && revision_rss_check_type($node)) {
    $feed_url = url("node/{$node->nid}/revisions/rss");
    drupal_add_feed($feed_url, t('Updates to "@title"', array('@title' => $node->title))); 
  }
}

/**
 * Check if RSS should be available for the given node.
 *
 * @param $node The node object to check against.
 *
 * @return bool True if RSS should be available for this node type, false otherwise.
 */
function revision_rss_check_type($node) {
  return in_array($node->type, variable_get('revision_rss_nodetypes', array('page')));
}