<?php
// $Id: revisions_rss.module,v 1.4 2009/01/21 21:29:18 alexj Exp $

/**
 * @file
 * Revision RSS, written by Alex Jarvis
 */

define('REV_RSS_PERM', 'view revision rss');

/*
 * Adds a permission for viewing RSS revisions.
 */
function revisions_rss_perm() {
  return array(REV_RSS_PERM);
}

/**
 * Implementation of hook_menu().
 */
function revisions_rss_menu() {
  $items = array();

  $items['admin/content/rss-publishing/default'] = array(
    'title' => 'General settings',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/content/rss-publishing/revision-rss'] = array(
    'title' => 'Revision RSS publishing',
    'description' => 'Configure RSS feeds for revisions.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('revision_rss_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'file' => 'revisions_rss.admin.inc',
  );
  $items['node/%node/revisions/rss'] = array(
    'title' => '',
    'page callback' => 'revisions_rss_handler',
    'page arguments' => array(1),
    'access arguments' => array(REV_RSS_PERM),
    'type' => MENU_CALLBACK,
    'file' => 'revisions_rss.pages.inc',
  );

  return $items;
}

/**
 * Implementation of hook_init().
 */
function revisions_rss_init() {
  // Expose node feed on node view page.
  if ((arg(0) == 'node') && is_numeric($nid = arg(1)) && is_null(arg(2)) &&
      ($node = node_load($nid)) && revision_rss_check_type($node) &&
      user_access(REV_RSS_PERM)) {

    drupal_add_feed(url("node/{$node->nid}/revisions/rss"),
                    t('Updates to "@title"', array('@title' => $node->title))
    );
  }
}

/**
 * Check if RSS should be available for the given node.
 *
 * @param $node The node object to check against.
 *
 * @return bool True if RSS should be available for this node type, false otherwise.
 */
function revision_rss_check_type($node) {
  return $node->nid && in_array($node->type, variable_get('revision_rss_nodetypes', array('page')));
}